#!/bin/bash

caps="$(cat /sys/class/leds/input3::capslock/brightness || cat /sys/class/leds/input10::capslock/brightness)"

if [ "$caps" == "1" ]; then
  echo '{"text": "A", "class": "caps-on", "tooltip": "Caps Lock is ON","alt":"1"}'
else
  echo '{"text": "a", "class": "caps-off", "tooltip": "Caps Lock is OFF","alt":"0"}'
fi
