#!/bin/bash

led="/sys/class/leds/"
key=$(ls "$led" | grep "capslock" | head -n 1)
caps=$(cat "$led$key/brightness")

if [ "$caps" == "1" ]; then
  echo '{"text": "A", "class": "caps-on", "tooltip": "Caps Lock is ON","alt":"1"}'
else
  echo '{"text": "a", "class": "caps-off", "tooltip": "Caps Lock is OFF","alt":"0"}'
fi
